env:
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
plugins:
  - mocha
parserOptions:
  sourceType: module
  ecmaFeatures:
    modules: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
